### ISSUE TITLE
Remove the "Users" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#322]
I don't believe this is very useful in future versions of Permissions:
<img width="1023" alt="Screen Shot 2021-02-04 at 2 17 48 PM" src="https://user-images.githubusercontent.com/3868028/106943771-daddff00-66f3-11eb-9168-35a28e4a3eeb.png">

**Comment by agapetry** [comment]
Since it's not immediately obvious that links on the Users and Edit User screen allow permissions to be assigned directly to a user, we will need to replace the Users screen with some other means of clarification. From experience, I can say that the questions about how to customize individual users will find their way to support if we don't answer it in the UI.

Also consider that on sites that do customize specific users, administrative review would be more challenging if there's no way to get a quick review of where permissions are coming from.  The links on the Users screen could easily be moved to a less prominent location, but will have value to some administrators.

**Comment by stevejburge** [comment]
@agapetry Let's do some planning on Slack and figure out how to handle this screen
