### ISSUE TITLE
Too many post types exposed by the "Core" tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#59]
> Settings > Core
> 
> Oh, Posts and pages are selected by default, so I am ready to go at a basic level -- I think. What are these other CPTs? Lazy Blocks? Subscribed Feeds? I have no idea what many of them are offhand, since other plugins created them on my local test install. :-)
<img width="354" alt="Screen Shot 2019-11-27 at 11 49 01 AM" src="https://user-images.githubusercontent.com/3868028/69743136-eb681200-110b-11ea-9d6a-c7e9b06ca50c.png">

**Comment by agapetry** [comment]
Hmm, I'm not sure what to say about that. I see your point, but on the other hand:

- Broad compatibility to customize post types unknown to us is one of the plugin's key values
- This has to be an opt-in because:
-- Enabling filtering causes new requirements to be imposed; permissions need to be designated
-- Our compatibility is with the WordPress API, but it's always possible for a plugin to throw their own incompatible twist into the editing UI or update operation. Without a deliberate opt-in, the user had no clue what went wrong.

**Comment by stevejburge** [comment]
@agapetry Sorry, this was a quote from a user. I'm happy to close this one
