### ISSUE TITLE
Retire Statuses in PublishPress, Move Permissions Statuses to Free

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#753]
I'd like to propose that we retire the statuses feature in the PublishPress plugin. Essentially we allow users to keep their current custom statuses, but remove the "Add New" button.

To replace this, we move Statuses to the free version of Permissions.

**Comment by agapetry** [comment]
> we allow users to keep their current custom statuses, but remove the "Add New" button

@stevejburge Can you confirm that I'm interpreting this well?

**If Permissions 3.9.x is active on its own (without PublishPress):**
- Pitch, Assigned, In Progress, and user-defined PP statuses are supported
- Configuration is through Permissions > Statuses, with a settings panel similar to the current PublishPress > Settings > Statuses UI
- Existing Permissions > Statuses and Permissions > Settings > Statuses UI is incorporated into a unified Permisions > Statuses screen using the PublishPress design paradigm.

**If PublishPress is active alongside Permissions 3.9.x:**
- No Statuses UI appears within PublishPress > Settings > Statuses (since it has been moved to Permissions > Statuses)

**If PublishPress is active on its own (without Permissions 3.9.x):**
- Pitch, Assigned, In Progress, and user-defined PP statuses remain functional without Permissions active
- Pitch, Assigned, In Progress, and user-defined PP statuses can be edited and configured within PublishPress > Settings as currently
- No new statuses can be defined

Is that correct? If this is the long-term plan, we should implement it with a new vendor library that can be shared between PublishPress and Permissions.

**Comment by stevejburge** [comment]
@agapetry Thanks for summarizing that well.

Yes, that's correct. PublishPress will essentially become display-only (adding icons and colors for the Calendar).

Permissions will become the single source of control for creating and managing statuses.

**Comment by agapetry** [comment]
Okay, so PublishPress > Settings > Statuses will remain for Calendar-specific configuration. In that case, that tab can also include a hint to avoid transitional confusion:

- A link to Permissions > Statuses if it's active
- A prompt to activate or install Permissions if it's not

**Comment by stevejburge** [comment]
@agapetry Yes, please. We can use our sidebar banner for this.

**Comment by agapetry** [comment]
'Resolved by PublishPress Statuses release and integrations.
