### ISSUE TITLE
Improve the Groups tab

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Permissions#81]
The "Groups" tab uses an old and funky way of searching for and selecting groups.

Can we make this "Select Groups" feature easier to use? Maybe a select box?

![Screen Shot 2020-04-20 at 1 23 26 PM](https://user-images.githubusercontent.com/3868028/79780856-915e2800-830a-11ea-9c57-dca3ce694365.png)

**Comment by htmgarcia** [comment]
@agapetry what do you think about displaying by default all the available custom groups (all of them with the default access), this in order to save a few steps?
<img width="387" alt="Screen Shot 2020-04-22 at 11 40 25" src="https://user-images.githubusercontent.com/4999794/80009139-466d1d80-848e-11ea-8ea9-1c1b6016395c.png">
I appreciate your thoughts before to do any change, Kevin.

**Comment by stevejburge** [comment]
@htmgarcia that make sense to me. 

This would only be a problem if people have 100's of groups and that's unlikely

**Comment by agapetry** [comment]
I think it could go either way. The advantage of the current behavior is that only customizations are displayed.  That makes review easier, since you don't have to visually scan to determine what groups have customized access.  It does add some extra setup steps, as you noted.  To me, displaying them all seems like a net benefit if there are up to 8 or 10 groups, but less so if there are more.  On a long list, displaying customized groups at the top would help, but maybe also add some disorientation for some users?  It seems we will still need some kind of search / paging functionality on the Users tab. So maybe just use the same "per page" limit on both tabs to decide whether to show all groups? Just my initial thoughts.

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/0c3690a9e528f5ff1dc2904f9d420897be876fdb

**Comment by htmgarcia** [comment]
https://github.com/publishpress/PublishPress-Permissions/commit/32e4ef54fb9573ce70a09a470120f896b9124a5b

**Comment by htmgarcia** [comment]
@stevejburge @agapetry you guys made a good point about the number of custom groups. Small improvements is safer:
<img width="575" alt="Screen Shot 2020-04-23 at 17 55 03" src="https://user-images.githubusercontent.com/4999794/80157505-f4aabd00-858b-11ea-894d-4b4c0ed4314f.png">
